tlo:
    image: kurron/docker-rancher-simulation-producer:1.0.0
    ports:
        - 8080
    log_driver: gelf
    log_opt:
        gelf-address: "udp://localhost:12201"
        tag: "TLO"
        labels: "foo,bar"
    environment:
        PRODUCER_REALM: ${PRODUCER_REALM}
        PRODUCER_FAIL: ${PRODUCER_FAIL}
        SPRING_CLOUD_CONFIG_URI: ${SPRING_CLOUD_CONFIG_URI}
        SPRING_CLOUD_RABBITMQ_HOST: ${SPRING_CLOUD_RABBITMQ_HOST}
        SPRING_CLOUD_DATASOURCE_URL: ${SPRING_CLOUD_DATASOURCE_URL}
        SPRING_CLOUD_DATASOURCE_USERNAME: ${SPRING_CLOUD_DATASOURCE_USERNAME}
        SPRING_CLOUD_DATASOURCE_PASSWORD: ${SPRING_CLOUD_DATASOURCE_PASSWORD}

