mysql:
    image: mysql:5.7.11
    ports:
        - 3306:3306
    log_driver: gelf
    log_opt:
        gelf-address: "udp://localhost:12201"
        tag: "MySQL"
        labels: "foo,bar"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}

