rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
        - 5672:5672
        - 15672:15672
        - 25672:25672
    log_driver: gelf
    log_opt:
        gelf-address: "udp://localhost:12201"
        tag: "RabbitMQ"
        labels: "foo,bar"
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}

