name: MySQL 
description: |
    The world's most popular open source database .
version: 5.7.11 
category: Development
maintainer: rkurr@jvmguy.com
license: Apache 2.0
projectURL: https://www.mysql.com/
