name: Reporting 
description: |
    The report generation portion of the Rancher simulation.
version: 1.0.1
category: Development
maintainer: rkurr@jvmguy.com
license: Apache 2.0
projectURL: https://github.com/kurron/rancher-simulation-consumer
