rabbitmq:
    image: rabbitmq:3.6.1-management
    ports:
        - 5672:5672
        - 15672:15672
        - 25672:25672
    environment:
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
        RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}

